### ISSUE TITLE
Cannot Run Locally: main.ts fails to build

### ISSUE THREAD

**Issue by mfisher31** [whxaxes/slither#9]
console output when running npm run dev

`[0] Hash: b4a4bd49afd44cb348c6
[0] Version: webpack 1.14.0
[0] Time: 1179ms
[0]            Asset       Size  Chunks       Chunk Names
[0]   main.bundle.js  195 bytes       0       main
[0] vendor.bundle.js    1.05 MB       1       vendor
[0]
[0] ERROR in ./src/main.ts
[0] Module build failed: TypeError: Cannot read property 'exclude' of undefined
[0]     at applyDefaults (/Users/mfisher/workspace/kushview/sleeether/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
[0]     at Object.ensureInstance (/Users/mfisher/workspace/kushview/sleeether/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
[0]     at compiler (/Users/mfisher/workspace/kushview/sleeether/node_modules/awesome-typescript-loader/src/index.ts:37:20)
[0]     at Object.loader (/Users/mfisher/workspace/kushview/sleeether/node_modules/awesome-typescript-loader/src/index.ts:18:18)
[0]  @ multi main`

**Comment by Roeefl** [comment]
Same here.
